[ColorScheme]
active_colors={fg}, {bg}, #ffffff, #cacaca, #9f9f9f, #b8b8b8, {fg}, #ffffff, {fg}, {bg}, {bg}, {color0}, {color1}, {bg}, {fg}, {color2}, {bg}, #000000, {bg}, {fg}, {color2}
disabled_colors={fg}, {bg}, #ffffff, #cacaca, #9f9f9f, #b8b8b8, {fg}, #ffffff, {fg}, {bg}, {bg}, {color0}, {color1}, {bg}, {fg}, {color2}, {bg}, #000000, {bg}, {fg}, {color2}
inactive_colors={fg}, {bg}, #ffffff, #cacaca, #9f9f9f, #b8b8b8, {fg}, #ffffff, {fg}, {bg}, {bg}, {color0}, {color1}, {bg}, {fg}, {color2}, {bg}, #000000, {bg}, {fg}, {color2}

