[config]

[config.wallpaper]
set = true
command = "awww img --transition-type none {{ image }}"


[templates.kitty]
input_path = '/home/hamato/.config/matugen/templates/colors-kitty.conf'
output_path = '/home/hamato/.config/matugen/generated/colors-kitty.conf' 
post_hook = '''
      ln -nfs "/home/hamato/.config/matugen/generated/colors-kitty.conf" "/home/hamato/.config/kitty/kitty-colors.conf"
      pkill -USR1 kitty
'''
[templates.gtk3]
input_path = '/home/hamato/.config/matugen/templates/gtk-colors.css'
output_path = '/home/hamato/.config/matugen/generated/gtk-colors.css'
post_hook = '''
      ln -nfs "/home/hamato/.config/matugen/generated/gtk-colors.css" "/home/hamato/.config/gtk-3.0/gtk.css"
      gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3" || :
'''

[templates.gtk4]
input_path = '/home/hamato/.config/matugen/templates/gtk-colors.css'
output_path = '/home/hamato/.config/matugen/generated/gtk-colors.css'
post_hook = '''
      ln -nfs "/home/hamato/.config/matugen/generated/gtk-colors.css" "/home/hamato/.config/gtk-4.0/gtk.css"
      gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3" || :
'''
[templates.qt5]
input_path = '/home/hamato/.config/matugen/templates/qtct-colors.conf'
output_path = '/home/hamato/.config/matugen/generated/qtct-colors.conf'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/qtct-colors.conf" "/home/hamato/.config/qt5ct/colors/pywal.conf"
'''
[templates.qt6]
input_path = '/home/hamato/.config/matugen/templates/qtct-colors.conf'
output_path = '/home/hamato/.config/matugen/generated/qtct-colors.conf'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/qtct-colors.conf" "/home/hamato/.config/qt6ct/colors/pywal.conf"
'''

[templates.waybarconf]
input_path = '/home/hamato/.config/matugen/templates/config.jsonc'
output_path = '/home/hamato/.config/matugen/generated/config.jsonc'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/config.jsonc" "/home/hamato/.config/waybar/config.jsonc"
       pkill -SIGUSR2 waybar
'''

[templates.waybarstyle]
input_path = '/home/hamato/.config/matugen/templates/style.css'
output_path = '/home/hamato/.config/matugen/generated/style.css'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/style.css" "/home/hamato/.config/waybar/style.css"
'''
[templates.vpn]
input_path = '/home/hamato/.config/matugen/templates/vpn-status.sh'
output_path = '/home/hamato/.config/matugen/generated/vpn-status.sh'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/vpn-status.sh" "/home/hamato/scripts/vpn-status.sh"
'''

[templates.cava]
input_path = '/home/hamato/.config/matugen/templates/cava-colors.ini'
output_path = '/home/hamato/.config/matugen/generated/cava-colors.ini'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/cava-colors.ini" "/home/hamato/.config/cava/themes/cava-colors.ini"
       pkill -USR1 cava
'''
[templates.btop]
input_path = '/home/hamato/.config/matugen/templates/btop.theme'
output_path = '/home/hamato/.config/matugen/generated/btop.theme'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/btop.theme" "/home/hamato/.config/btop/themes/matugen.theme"
       pkill -USR2 btop
'''

[templates.easyeffects]
input_path = '/home/hamato/.config/matugen/templates/easyeffectsrc'
output_path = '/home/hamato/.config/matugen/generated/easyeffectsrc'
post_hook = '''
       cp -r "/home/hamato/.config/matugen/generated/easyeffects" "/home/hamato/.config/easyeffectsrc"
'''
[templates.mako]
input_path = '/home/hamato/.config/matugen/templates/colors-mako'
output_path = '/home/hamato/.config/matugen/generated/colors-mako'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/colors-mako" "/home/hamato/.config/mako/config"
       pkill mako && mako &
'''
[templates.kdeglobals]
input_path = '/home/hamato/.config/matugen/templates/kdeglobals'
output_path = '/home/hamato/.config/matugen/generated/kdeglobals'
post_hook = '''
       cp -r "/home/hamato/.config/matugen/generated/kdeglobals" "/home/hamato/.config/kdeglobals"
'''
[templates.pywalfox]
input_path = '/home/hamato/.config/matugen/templates/pywalfox-colors.json'
output_path = '/home/hamato/.config/matugen/generated/pywalfox-colors.json'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/pywalfox-colors.json" "/home/hamato/.cache/wal/colors.json"
       pywalfox update
'''
[templates.rofi]
input_path = '/home/hamato/.config/matugen/templates/rofi-config.rasi'
output_path = '/home/hamato/.config/matugen/generated/rofi-config.rasi'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/rofi-config.rasi" "/home/hamato/.config/rofi/config.rasi"
'''
[templates.nvim]
input_path = '/home/hamato/.config/matugen/templates/colors.vim'
output_path = '/home/hamato/.config/matugen/generated/colors.vim'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/colors.vim" "/home/hamato/.cache/wal/colors-wal.vim"
       pkill -SIGUSR1 -x nvim || :
'''
[templates.zathura]
input_path = '/home/hamato/.config/matugen/templates/zathura-colors'
output_path = '/home/hamato/.config/matugen/generated/zathura-colors'
post_hook = '''
       ln -nfs "/home/hamato/.config/matugen/generated/zathura-colors" "/home/hamato/.config/zathura/zathurarc"
'''




