# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#575279"

# Title color for boxes
theme[title]="#56949f"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ea9d34"

# Background color of selected item in processes box
theme[selected_bg]="#b4637a"

# Foreground color of selected item in processes box
theme[selected_fg]="#faf4ed"

# Color of inactive/disabled text
theme[inactive_fg]="#907aa9"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{colors.tertiary.default.hex}}"

# Cpu box outline color
theme[cpu_box]="#575279"

# Memory/disks box outline color
theme[mem_box]="#575279"

# Net up/down box outline color
theme[net_box]="#575279"

# Processes box outline color
theme[proc_box]="#575279"

# Box divider line and small boxes line color
theme[div_line]="#d7827e"

# Temperature graph colors
theme[temp_start]="#ea9d34"
theme[temp_mid]="#56949f"
theme[temp_end]="#b4637a"

# CPU graph colors
theme[cpu_start]="#ea9d34"
theme[cpu_mid]="#56949f"
theme[cpu_end]="#b4637a"

# Mem/Disk free meter
theme[free_start]="#ea9d34"
theme[free_mid]="#56949f"
theme[free_end]="#b4637a"

# Mem/Disk cached meter
theme[cached_start]="#ea9d34"
theme[cached_mid]="#56949f"
theme[cached_end]="#b4637a"

# Mem/Disk available meter
theme[available_start]="#ea9d34"
theme[available_mid]="#56949f"
theme[available_end]="#b4637a"

# Mem/Disk used meter
theme[used_start]="#ea9d34"
theme[used_mid]="#56949f"
theme[used_end]="#b4637a"

# Download graph colors
theme[download_start]="#ea9d34"
theme[download_mid]="#56949f"
theme[download_end]="#b4637a"

# Upload graph colors
theme[upload_start]="#ea9d34"
theme[upload_mid]="#56949f"
theme[upload_end]="#b4637a"
