# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0def4"

# Title color for boxes
theme[title]="#9ccfd8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{colors.secondary.default.hex}}"

# Background color of selected item in processes box
theme[selected_bg]="#eb6f92"

# Foreground color of selected item in processes box
theme[selected_fg]="#191724"

# Color of inactive/disabled text
theme[inactive_fg]="#c4a7e7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{colors.tertiary.default.hex}}"

# Cpu box outline color
theme[cpu_box]="#e0def4"

# Memory/disks box outline color
theme[mem_box]="#e0def4"

# Net up/down box outline color
theme[net_box]="#e0def4"

# Processes box outline color
theme[proc_box]="#e0def4"

# Box divider line and small boxes line color
theme[div_line]="#ebbcba"

# Temperature graph colors
theme[temp_start]="#f6c177"
theme[temp_mid]="#9ccfd8"
theme[temp_end]="#eb6f92"

# CPU graph colors
theme[cpu_start]="#f6c177"
theme[cpu_mid]="#9ccfd8"
theme[cpu_end]="#eb6f92"

# Mem/Disk free meter
theme[free_start]="{{colors.secondary.default.hex}}"
theme[free_mid]=""
theme[free_end]="{{colors.secondary_container.default.hex}}"

# Mem/Disk cached meter
theme[cached_start]="{{colors.tertiary.default.hex}}"
theme[cached_mid]=""
theme[cached_end]="{{colors.tertiary_container.default.hex}}"

# Mem/Disk available meter
theme[available_start]="#f6c177"
theme[available_mid]=""
theme[available_end]="#eb6f92"

# Mem/Disk used meter
theme[used_start]="#f6c177"
theme[used_mid]=""
theme[used_end]="#eb6f92"

# Download graph colors
theme[download_start]="#f6c177"
theme[download_mid]="#9ccfd8"
theme[download_end]="#eb6f92"

# Upload graph colors
theme[upload_start]="#f6c177"
theme[upload_mid]="#9ccfd8"
theme[upload_end]="#eb6f92"
