# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#ffffff"

# Title color for boxes
theme[title]="#ebcf18"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{colors.secondary.default.hex}}"

# Background color of selected item in processes box
theme[selected_bg]="#c9ad3e"

# Foreground color of selected item in processes box
theme[selected_fg]="#121212"

# Color of inactive/disabled text
theme[inactive_fg]="#0e85d8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{colors.tertiary.default.hex}}"

# Cpu box outline color
theme[cpu_box]="#ffffff"

# Memory/disks box outline color
theme[mem_box]="#ffffff"

# Net up/down box outline color
theme[net_box]="#ffffff"

# Processes box outline color
theme[proc_box]="#ffffff"

# Box divider line and small boxes line color
theme[div_line]="#1cb8d5"

# Temperature graph colors
theme[temp_start]="#23cbe4"
theme[temp_mid]="#ebcf18"
theme[temp_end]="#c9ad3e"

# CPU graph colors
theme[cpu_start]="#23cbe4"
theme[cpu_mid]="#ebcf18"
theme[cpu_end]="#c9ad3e"

# Mem/Disk free meter
theme[free_start]="{{colors.secondary.default.hex}}"
theme[free_mid]=""
theme[free_end]="{{colors.secondary_container.default.hex}}"

# Mem/Disk cached meter
theme[cached_start]="{{colors.tertiary.default.hex}}"
theme[cached_mid]=""
theme[cached_end]="{{colors.tertiary_container.default.hex}}"

# Mem/Disk available meter
theme[available_start]="#23cbe4"
theme[available_mid]=""
theme[available_end]="#c9ad3e"

# Mem/Disk used meter
theme[used_start]="#23cbe4"
theme[used_mid]=""
theme[used_end]="#c9ad3e"

# Download graph colors
theme[download_start]="#23cbe4"
theme[download_mid]="#ebcf18"
theme[download_end]="#c9ad3e"

# Upload graph colors
theme[upload_start]="#23cbe4"
theme[upload_mid]="#ebcf18"
theme[upload_end]="#c9ad3e"
