[color]
background = '#041010'
foreground = '#8c7666'

; gradient = 0
gradient = 1
gradient_color_1 = '#8c7666'
gradient_color_2 = '#a28e7c'
gradient_color_3 = '#6f806d'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#8c7666'
horizontal_gradient_color_2 = '#a28e7c'
horizontal_gradient_color_3 = '#6f806d'
horizontal_gradient_color_4 = '#a28e7c'
horizontal_gradient_color_5 = '#8c7666'


