[color]
background = '#070204'
foreground = '#d7397d'

; gradient = 0
gradient = 1
gradient_color_1 = '#d7397d'
gradient_color_2 = '#ff609d'
gradient_color_3 = '#f05291'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#d7397d'
horizontal_gradient_color_2 = '#ff609d'
horizontal_gradient_color_3 = '#f05291'
horizontal_gradient_color_4 = '#ff609d'
horizontal_gradient_color_5 = '#d7397d'


