[color]
background = '#e6abc7'
foreground = '#89555a'

; gradient = 0
gradient = 1
gradient_color_1 = '#89555a'
gradient_color_2 = '#696932'
gradient_color_3 = '#7a6f3d'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#89555a'
horizontal_gradient_color_2 = '#696932'
horizontal_gradient_color_3 = '#7a6f3d'
horizontal_gradient_color_4 = '#696932'
horizontal_gradient_color_5 = '#89555a'


