# UI Colors (extended)
accent = "#a9aacf"
cursor = "#d4c7e3"

# Primary colors
foreground = "#d4c7e3"
background = "#131520"

# Selection colors
selection_foreground = "#131520"
selection_background = "#d4c7e3"

# Normal colors (ANSI 0-7)
color0 = "#131520"
color1 = "#cd98b7"
color2 = "#beb7e5"
color3 = "#ebb4d4"
color4 = "#a9aacf"
color5 = "#cea4ce"
color6 = "#c2bae6"
color7 = "#d4c7e3"

# Bright colors (ANSI 8-15)
color8 = "#707177"
color9 = "#f5b7df"
color10 = "#cdbdff"
color11 = "#ffb5ec"
color12 = "#cac9f8"
color13 = "#efbdf3"
color14 = "#d1c0ff"
color15 = "#e8ccff"
