foreground         #d4c7e3
background         #131520
cursor             #cd98b7

active_tab_foreground     #131520
active_tab_background     #d4c7e3
inactive_tab_foreground   #d4c7e3
inactive_tab_background   #131520

active_border_color   #d4c7e3
inactive_border_color #131520
bell_border_color     #cd98b7

color0       #131520
color8       #707177
color1       #cd98b7
color9       #f5b7df
color2       #beb7e5
color10      #cdbdff
color3       #ebb4d4
color11      #ffb5ec
color4       #a9aacf
color12      #cac9f8
color5       #cea4ce
color13      #efbdf3
color6       #c2bae6
color14      #d1c0ff
color7       #d4c7e3
color15      #e8ccff
