foreground         #ECBEB8
background         #140002
cursor             #e1404a

active_tab_foreground     #140002
active_tab_background     #ECBEB8
inactive_tab_foreground   #ECBEB8
inactive_tab_background   #140002

active_border_color   #ECBEB8
inactive_border_color #140002
bell_border_color     #e1404a

color0       #140002
color8       #6f6767
color1       #e1404a
color9       #ff5f68
color2       #537e9c
color10      #73a2c9
color3       #e1404a
color11      #ff5f68
color4       #547fab
color12      #74a3db
color5       #83799b
color13      #a89bc7
color6       #527e9b
color14      #72a2c8
color7       #ECBEB8
color15      #ffc0b5
