foreground         #ffffff
background         #121212
cursor             #b66a5a

active_tab_foreground     #121212
active_tab_background     #ffffff
inactive_tab_foreground   #ffffff
inactive_tab_background   #121212

active_border_color   #ffffff
inactive_border_color #121212
bell_border_color     #b66a5a

color0       #121212
color8       #9e9e9e
color1       #b66a5a
color9       #e38c77
color2       #9b954b
color10      #bbb354
color3       #afa058
color11      #c4b56b
color4       #6583c1
color12      #87a6f5
color5       #b96579
color13      #e7859e
color6       #4b919b
color14      #54aebb
color7       #ffffff
color15      #ffffff
