[ColorScheme]
active_colors=#cdd6f4, #1e1e2e, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #cdd6f4, #ffffff, #cdd6f4, #1e1e2e, #1e1e2e, #1e1e2e, #f38ba8, #1e1e2e, #cdd6f4, #a6e3a1, #1e1e2e, #000000, #1e1e2e, #cdd6f4, #a6e3a1
disabled_colors=#cdd6f4, #1e1e2e, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #cdd6f4, #ffffff, #cdd6f4, #1e1e2e, #1e1e2e, #1e1e2e, #f38ba8, #1e1e2e, #cdd6f4, #a6e3a1, #1e1e2e, #000000, #1e1e2e, #cdd6f4, #a6e3a1
inactive_colors=#cdd6f4, #1e1e2e, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #cdd6f4, #ffffff, #cdd6f4, #1e1e2e, #1e1e2e, #1e1e2e, #f38ba8, #1e1e2e, #cdd6f4, #a6e3a1, #1e1e2e, #000000, #1e1e2e, #cdd6f4, #a6e3a1

