[color]
background = '#061513'
foreground = '#277401'

; gradient = 0
gradient = 1
gradient_color_1 = '#277401'
gradient_color_2 = '#246005'
gradient_color_3 = '#4c7605'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#277401'
horizontal_gradient_color_2 = '#246005'
horizontal_gradient_color_3 = '#4c7605'
horizontal_gradient_color_4 = '#246005'
horizontal_gradient_color_5 = '#277401'


