[color]
background = 'default'
foreground = '#7e570f'

; gradient = 0
gradient = 1
gradient_color_1 = '#ffddb0'
gradient_color_2 = '#7e570f'
gradient_color_3 = '#291800'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#ffddb0'
horizontal_gradient_color_2 = '#7e570f'
horizontal_gradient_color_3 = '#291800'
horizontal_gradient_color_4 = '#7e570f'
horizontal_gradient_color_5 = '#ffddb0'


