[color]
background = '#1b3755'
foreground = '#caac8f'

; gradient = 0
gradient = 1
gradient_color_1 = '#caac8f'
gradient_color_2 = '#2e5270'
gradient_color_3 = '#234565'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#caac8f'
horizontal_gradient_color_2 = '#2e5270'
horizontal_gradient_color_3 = '#234565'
horizontal_gradient_color_4 = '#2e5270'
horizontal_gradient_color_5 = '#caac8f'


