foreground         #EAEAEA
background         #111111
cursor             #02A279

active_tab_foreground     #111111
active_tab_background     #EAEAEA
inactive_tab_foreground   #EAEAEA
inactive_tab_background   #111111

active_border_color   #EAEAEA
inactive_border_color #111111
bell_border_color     #090D0D

color0       #393939
color8       #989898
color1       #989898
color9       #0C1111
color2       #074737
color10      #0A5F49
color3       #283A3A
color11      #354D4D
color4       #02A279
color12      #02D8A1
color5       #426157
color13      #588274
color6       #66937C
color14      #88C4A6
color7       #D9D9D9
color15      #D9D9D9
