foreground         #a9697d
background         #04050a
cursor             #80444d


active_tab_foreground     #a9697d
active_tab_background     #04050a
inactive_tab_foreground   #a9697d
inactive_tab_background   #04050a

active_border_color   #80444d
inactive_border_color #a9697d
bell_border_color     #80444d

color0       #04050a
color8       #a9687c
color1       #1c131a
color9       #793941
color2       #33222b
color10      #3d2832
color3       #4b303b
color11      #211924
color4       #623e4c
color12      #140f1a
color5       #7a4c5c
color13      #18121d
color6       #915b6c
color14      #120d18
color7       #a9697d
color15      #0f0c16
