foreground         #04cccc
background         #043a40
cursor             #06d7b4


active_tab_foreground     #04cccc
active_tab_background     #043a40
inactive_tab_foreground   #04cccc
inactive_tab_background   #043a40

active_border_color   #06d7b4
inactive_border_color #04cccc
bell_border_color     #06d7b4

color0       #043a40
color8       #03cbcc
color1       #044e54
color9       #01bdc0
color2       #046368
color10      #02b4b9
color3       #04787c
color11      #01b2b9
color4       #048d90
color12      #02b2b9
color5       #04a2a4
color13      #02b2b9
color6       #04b7b8
color14      #02b2b9
color7       #04cccc
color15      #01b0b7
