[ColorScheme]
active_colors=#6D6A5C, #D5CACF, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #6D6A5C, #ffffff, #6D6A5C, #D5CACF, #D5CACF, #B9AEB4, #A78A72, #D5CACF, #6D6A5C, #E0B668, #D5CACF, #000000, #D5CACF, #6D6A5C, #E0B668
disabled_colors=#6D6A5C, #D5CACF, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #6D6A5C, #ffffff, #6D6A5C, #D5CACF, #D5CACF, #B9AEB4, #A78A72, #D5CACF, #6D6A5C, #E0B668, #D5CACF, #000000, #D5CACF, #6D6A5C, #E0B668
inactive_colors=#6D6A5C, #D5CACF, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #6D6A5C, #ffffff, #6D6A5C, #D5CACF, #D5CACF, #B9AEB4, #A78A72, #D5CACF, #6D6A5C, #E0B668, #D5CACF, #000000, #D5CACF, #6D6A5C, #E0B668

