[mgr]
cwd = { 
  fg = "#3B2657" 
  }
# Border
border_symbol = ""
border_style  = { 
  fg = "#3B2657" 
  }


[indicator]
padding = {
  open = "█", 
  close = "█" 
}
current = { 
  fg = "#201921", 
  bg = "#3B3F5F"
}
parent = { 
  fg = "#201921", 
  bg = "#3B3F5F"
}
preview = { 
  fg = "#201921", 
  bg = "#3B3F5F"
}

[status]
sep_left  = { 
  open = "█", 
  close = "█" 
}
sep_right = { 
  open = "█", 
  close = "█" 
}

[mode]
#Mode
normal_main = { 
  bg = "#A11F45", 
  fg = "#201921", 
  bold = true 
}
normal_alt  = { 
  bg = "#3B2657", 
  fg = "#201921" 
}

[tabs]
active    = { 
  fg = "#201921", 
  bold = true, 
  bg = "#3B2657" 
}
inactive  = { 
  fg = "#3B2657", 
  bg = "#201921" 
}
sep_inner = { 
  open = "█",
  close = "█" 
}

[icon]

dirs  = [ 
 	{ name = 
    ".config", 
  text = "", 
  fg = "#3B2657" 
}, 
 	{ name = "Wallpapers", text = "", fg = "#3B2657" }, 
 	{ name = "scripts", text = "", fg = "#3B2657" }, 
 	{ name = "Games", text = "", fg = "#3B2657" }, 
 	{ 
    name = "Desktop", 
    text = "", 
    fg = "#3B2657" 
  }, 
 	{ name = "Development", text = "", fg = "#3B2657" }, 
 	{ name = "Documents", text = "", fg = "#3B2657" }, 
 	{ name = "Downloads", text = "", fg = "#3B2657" }, 
 	{ name = "Library", text = "", fg = "#3B2657" }, 
 	{ name = "Movies", text = "", fg = "#3B2657" }, 
 	{ name = "Music", text = "", fg = "#3B2657" }, 
 	{ name = "Pictures", text = "", fg = "#3B2657" }, 
 	{ name = "Public", text = "", fg = "#3B2657" }, 
 	{ name = "Videos", text = "", fg = "#3B2657" },
  { name = "Storage",text = "",  fg = "#3B2657"},  
 ] 


