[mgr]
cwd = { 
  fg = "#283A3A" 
  }
# Border
border_symbol = ""
border_style  = { 
  fg = "#283A3A" 
  }


[indicator]
padding = {
  open = "█", 
  close = "█" 
}
current = { 
  fg = "#111111", 
  bg = "#02A279"
}
parent = { 
  fg = "#111111", 
  bg = "#02A279"
}
preview = { 
  fg = "#111111", 
  bg = "#02A279"
}

[status]
sep_left  = { 
  open = "█", 
  close = "█" 
}
sep_right = { 
  open = "█", 
  close = "█" 
}

[mode]
#Mode
normal_main = { 
  bg = "#426157", 
  fg = "#111111", 
  bold = true 
}
normal_alt  = { 
  bg = "#283A3A", 
  fg = "#111111" 
}

[tabs]
active    = { 
  fg = "#111111", 
  bold = true, 
  bg = "#283A3A" 
}
inactive  = { 
  fg = "#283A3A", 
  bg = "#111111" 
}
sep_inner = { 
  open = "█",
  close = "█" 
}

[icon]

dirs  = [ 
 	{ name = 
    ".config", 
  text = "", 
  fg = "#283A3A" 
}, 
 	{ name = "Wallpapers", text = "", fg = "#283A3A" }, 
 	{ name = "scripts", text = "", fg = "#283A3A" }, 
 	{ name = "Games", text = "", fg = "#283A3A" }, 
 	{ 
    name = "Desktop", 
    text = "", 
    fg = "#283A3A" 
  }, 
 	{ name = "Development", text = "", fg = "#283A3A" }, 
 	{ name = "Documents", text = "", fg = "#283A3A" }, 
 	{ name = "Downloads", text = "", fg = "#283A3A" }, 
 	{ name = "Library", text = "", fg = "#283A3A" }, 
 	{ name = "Movies", text = "", fg = "#283A3A" }, 
 	{ name = "Music", text = "", fg = "#283A3A" }, 
 	{ name = "Pictures", text = "", fg = "#283A3A" }, 
 	{ name = "Public", text = "", fg = "#283A3A" }, 
 	{ name = "Videos", text = "", fg = "#283A3A" },
  { name = "Storage",text = "",  fg = "#283A3A"},  
 ] 


