[mgr]
cwd = { fg = "#10abb3" }
# Border
border_symbol = ""
border_style  = { fg = "#10abb3" }


[indicator]
padding = { open = "█", close = "█" }
current = { fg = "#e8fbdf", bg = "#25adae"}
parent = { fg = "#e8fbdf", bg = "#25adae"}
preview = { fg = "#e8fbdf", bg = "#25adae"}

[status]
sep_left  = { open = "█", close = "█" }
sep_right = { open = "█", close = "█" }

[mode]
#Mode
normal_main = { bg = "#25adae", fg = "#e8fbdf", bold = true }
normal_alt  = { bg = "#10abb3", fg = "#e8fbdf" }

[tabs]
active    = { fg = "#e8fbdf", bold = true, bg = "#10abb3" }
inactive  = { fg = "#10abb3", bg = "#e8fbdf" }
sep_inner = { open = "█",close = "█" }

[icon]

dirs  = [ 
 	{ name = ".config", text = "", fg = "#10abb3" }, 
 	{ name = "Wallpapers", text = "", fg = "#10abb3" }, 
 	{ name = "scripts", text = "", fg = "#10abb3" }, 
 	{ name = "Games", text = "", fg = "#10abb3" }, 
 	{ name = "Desktop", text = "", fg = "#10abb3" }, 
 	{ name = "Development", text = "", fg = "#10abb3" }, 
 	{ name = "Documents", text = "", fg = "#10abb3" }, 
 	{ name = "Downloads", text = "", fg = "#10abb3" }, 
 	{ name = "Library", text = "", fg = "#10abb3" }, 
 	{ name = "Movies", text = "", fg = "#10abb3" }, 
 	{ name = "Music", text = "", fg = "#10abb3" }, 
 	{ name = "Pictures", text = "", fg = "#10abb3" }, 
 	{ name = "Public", text = "", fg = "#10abb3" }, 
 	{ name = "Videos", text = "", fg = "#10abb3" },
  { name = "Storage",text = "",  fg = "#10abb3"},  
 ] 


