[color]
background = '#%% background.hex %%'
foreground = '#%% color1.hex %%'

; gradient = 0
gradient = 1
gradient_color_1 = '#%% color1.hex %%'
gradient_color_2 = '#%% color3.hex %%'
gradient_color_3 = '#%% color2.hex %%'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#%% color1.hex %%'
horizontal_gradient_color_2 = '#%% color3.hex %%'
horizontal_gradient_color_3 = '#%% color2.hex %%'
horizontal_gradient_color_4 = '#%% color3.hex %%'
horizontal_gradient_color_5 = '#%% color1.hex %%'


