[mgr]
cwd = { 
  fg = "#%% color3.hex %%" 
  }
# Border
border_symbol = ""
border_style  = { 
  fg = "#%% color3.hex %%" 
  }


[indicator]
padding = {
  open = "█", 
  close = "█" 
}
current = { 
  fg = "#%% background.hex %%", 
  bg = "#%% color1.hex %%"
}
parent = { 
  fg = "#%% background.hex %%", 
  bg = "#%% color1.hex %%"
}
preview = { 
  fg = "#%% background.hex %%", 
  bg = "#%% color1.hex %%"
}

[status]
sep_left  = { 
  open = "█", 
  close = "█" 
}
sep_right = { 
  open = "█", 
  close = "█" 
}

[mode]
#Mode
normal_main = { 
  bg = "#%% color1.hex %%", 
  fg = "#%% background.hex %%", 
  bold = true 
}
normal_alt  = { 
  bg = "#%% color3.hex %%", 
  fg = "#%% background.hex %%" 
}

[tabs]
active    = { 
  fg = "#%% background.hex %%", 
  bold = true, 
  bg = "#%% color3.hex %%" 
}
inactive  = { 
  fg = "#%% color3.hex %%", 
  bg = "#%% background.hex %%" 
}
sep_inner = { 
  open = "█",
  close = "█" 
}

[icon]

dirs  = [ 
 	{ name = 
    ".config", 
  text = "", 
  fg = "#%% color3.hex %%" 
}, 
 	{ name = "Wallpapers", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "scripts", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Games", text = "", fg = "#%% color3.hex %%" }, 
 	{ 
    name = "Desktop", 
    text = "", 
    fg = "#%% color3.hex %%" 
  }, 
 	{ name = "Development", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Documents", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Downloads", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Library", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Movies", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Music", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Pictures", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Public", text = "", fg = "#%% color3.hex %%" }, 
 	{ name = "Videos", text = "", fg = "#%% color3.hex %%" },
  { name = "Storage",text = "",  fg = "#%% color3.hex %%"},  
 ] 


